"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_ACTION_FONT_SIZE = exports.DEFAULT_ACTION_TEXT = exports.EXHALE_SIZE = exports.INHALE_SIZE = exports.HOLD = exports.EXHALE = exports.INHALE = exports.BREATH_CURVE = exports.SMOOTH_PATH_TIMING = exports.SMALL_CIRCLE_SIZE = exports.LARGE_CIRCLE_SIZE = exports.RESET_ORANGE = exports.EXHALE_COLOR = exports.INHALE_COLOR = exports.DEFAULT_BACKGROUND_COLOR = exports.timerDirection = exports.timerSecondsInput = exports.timerMinutesInput = exports.holdTimeInput = exports.breathTimeInput = exports.pauseButton = exports.stopButton = exports.start = exports.invisible = exports.action = exports.circle = exports.boxRect = exports.box = void 0;
exports.box = document.querySelector('.breath-box');
exports.boxRect = exports.box.getBoundingClientRect();
exports.circle = document.querySelector('.circle');
exports.action = document.querySelector('.action');
exports.invisible = document.querySelector('.invisible');
exports.start = document.querySelector('.timer-start');
exports.stopButton = document.querySelector('.stop');
exports.pauseButton = document.querySelector('.pause');
exports.breathTimeInput = document.querySelector('#breath-time');
exports.holdTimeInput = document.querySelector('#hold-time');
exports.timerMinutesInput = document.querySelector('#countdown-minutes');
exports.timerSecondsInput = document.querySelector('#countdown-seconds');
exports.timerDirection = document.querySelector('#time-arrow');
exports.DEFAULT_BACKGROUND_COLOR = "#1e3250";
exports.INHALE_COLOR = "#0f5362";
exports.EXHALE_COLOR = "#c08845";
exports.RESET_ORANGE = "#f6786e";
exports.LARGE_CIRCLE_SIZE = 6;
exports.SMALL_CIRCLE_SIZE = 2;
exports.SMOOTH_PATH_TIMING = 1000;
exports.BREATH_CURVE = "cubic-bezier(.13,.38,.48,1.02)";
exports.INHALE = "INHALE";
exports.EXHALE = "EXHALE";
exports.HOLD = "HOLD";
exports.INHALE_SIZE = 8;
exports.EXHALE_SIZE = 4;
exports.DEFAULT_ACTION_TEXT = "Breath Box";
exports.DEFAULT_ACTION_FONT_SIZE = "5vh";
//# sourceMappingURL=common.js.map