export declare const box: HTMLElement;
export declare const boxRect: DOMRect;
export declare const circle: HTMLElement;
export declare const action: HTMLElement;
export declare const invisible: HTMLElement;
export declare const start: HTMLElement;
export declare const stopButton: HTMLElement;
export declare const pauseButton: HTMLElement;
export declare const breathTimeInput: HTMLInputElement;
export declare const holdTimeInput: HTMLInputElement;
export declare const timerMinutesInput: HTMLInputElement;
export declare const timerSecondsInput: HTMLInputElement;
export declare const timerDirection: HTMLElement;
export declare const config: HTMLElement;
export declare const controlBar: HTMLElement;
export declare const DEFAULT_BACKGROUND_COLOR = "#1e3250";
export declare const INHALE_COLOR = "#0f5362";
export declare const EXHALE_COLOR = "#c08845";
export declare const RESET_ORANGE = "#f6786e";
export declare const LARGE_CIRCLE_SIZE = 6;
export declare const SMALL_CIRCLE_SIZE = 2;
export declare const SMOOTH_PATH_TIMING = 1000;
export declare const BREATH_CURVE = "cubic-bezier(.13,.38,.48,1.02)";
export declare const INHALE = "INHALE";
export declare const EXHALE = "EXHALE";
export declare const HOLD = "HOLD";
export declare const INHALE_SIZE = 8;
export declare const EXHALE_SIZE = 4;
export declare const DEFAULT_ACTION_TEXT = "Breath Box";
export declare const DEFAULT_ACTION_FONT_SIZE = "5vh";
