declare const box: HTMLElement;
declare const boxRect: DOMRect;
declare const circle: HTMLElement;
declare const action: HTMLElement;
declare const invisible: HTMLElement;
declare const start: HTMLElement;
declare const stopButton: HTMLElement;
declare const pauseButton: HTMLElement;
declare const DEFAULT_BACKGROUND_COLOR = "#1e3250";
declare const INHALE_COLOR = "#0f5362";
declare const EXHALE_COLOR = "#c08845";
declare const RESET_ORANGE = "#f6786e";
declare const LARGE_CIRCLE_SIZE = 6;
declare const SMALL_CIRCLE_SIZE = 2;
declare const SMOOTH_PATH_TIMING = 1000;
declare const BREATH_RATIO = 6;
declare const BREATH_CURVE = "cubic-bezier(.13,.38,.48,1.02)";
declare const HOLD_RATIO = 3;
declare const INHALE = "INHALE";
declare const EXHALE = "EXHALE";
declare const HOLD = "HOLD";
declare const INHALE_SIZE = 8;
declare const EXHALE_SIZE = 4;
declare const DEFAULT_ACTION_TEXT = "Breath Box";
declare const DEFAULT_ACTION_FONT_SIZE = "5vh";
