declare const box: HTMLElement;
declare const boxRect: DOMRect;
declare const circle: HTMLElement;
declare const action: HTMLElement;
declare const invisible: HTMLElement;
declare const start: HTMLElement;
declare const stopButton: HTMLElement;
declare const pauseButton: HTMLElement;
declare const DEFAULT_BACKGROUND_COLOR = "#1e3250";
declare const INHALE_COLOR = "#0f5362";
declare const EXHALE_COLOR = "#c08845";
declare const RESET_ORANGE = "#f6786e";
declare const LARGE_CIRCLE_SIZE = 6;
declare const SMALL_CIRCLE_SIZE = 2;
